<?php

namespace App\Http\Controllers\Internal;

use App\Http\Controllers\Controller;
use App\Http\Requests\UpdateProductionStatusRequest;
use App\Models\Notification;
use App\Models\Order;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ProductionController extends Controller
{
    public function index()
    {
        $orders = Order::with(['user', 'designRequest', 'orderItems', 'itemDetails', 'statusHistories'])
            ->whereIn('status', ['siap_cetak', 'diproduksi'])
            ->latest()
            ->get()
            ->map(function ($order) {
                $dr = $order->designRequest;

                $sizes = [];
                foreach ($order->orderItems as $item) {
                    $sizes[$item->size] = $item->qty;
                }

                $stage = $order->production_stage ?? 'printing';

                $priority = $dr?->priority ?? 'normal';

                // Collect production notes from status histories
                $prodHistoryNotes = $order->statusHistories
                    ->whereIn('status', ['siap_cetak', 'diproduksi'])
                    ->filter(fn($h) => !empty($h->notes) && !str_starts_with($h->notes, 'Status berubah'))
                    ->map(fn($h) => '[' . $h->created_at->format('d M H:i') . '] ' . $h->notes)
                    ->values();

                $originalNotes = $dr?->additional_notes ?? $order->notes;
                $cleanNotes = preg_replace('/^(Jenis Potongan:.*|Model Lengan & Jahitan:.*)\n?/m', '', $originalNotes);
                $cleanNotes = trim($cleanNotes);
                $allNotes = $cleanNotes
                    ? collect([$cleanNotes])->merge($prodHistoryNotes)->implode("\n\n")
                    : ($prodHistoryNotes->isNotEmpty() ? $prodHistoryNotes->implode("\n\n") : 'Tidak ada catatan');

                // History notes with origin
                $autoGeneratedPrefixes = [
                    'Status berubah menjadi',
                    'Produksi:',
                    'Design selesai',
                    'Pembayaran divalidasi',
                    'Desain disetujui',
                ];
                $historyNotes = [];
                foreach ($order->statusHistories as $h) {
                    $note = $h->notes;
                    if (empty($note)) continue;

                    $isAuto = false;
                    foreach ($autoGeneratedPrefixes as $prefix) {
                        if (str_starts_with($note, $prefix)) { $isAuto = true; break; }
                    }
                    if ($isAuto) continue;

                    $roleName = $h->changedBy?->role?->name;
                    $origin = match ($roleName) {
                        'Design'   => 'Design',
                        'Customer' => 'Customer',
                        'Produksi' => str_contains($note, 'printing') ? 'Produksi (Printing)'
                                    : (str_contains($note, 'jahit')    ? 'Produksi (Jahit)'
                                    : (str_contains($note, 'qc') || str_contains($note, 'QC') ? 'Produksi (QC)' : 'Produksi')),
                        null       => 'Sistem',
                        default    => $roleName,
                    };

                    $historyNotes[] = [
                        'date'   => $h->created_at->format('j M Y, H:i'),
                        'user'   => $h->changedBy?->name ?? 'Sistem',
                        'origin' => $origin,
                        'note'   => $note,
                    ];
                }

                return [
                    'id'                => $order->id,
                    'order_id'          => $order->order_number,
                    'customer'          => $order->user->name ?? '-',
                    'customer_contact'  => $order->user->phone ?? '-',
                    'team_name'         => $dr?->team_name ?? 'Jersey Custom',
                    'status'            => $order->status,
                    'production_stage'  => $stage,
                    'deadline'          => $order->created_at->addDays(7)->format('d M Y'),
                    'priority'          => $priority,
                    'material'          => $dr?->material ?? '-',
                    'collar'            => $dr?->collar_style ?? '-',
                    'pattern'           => $dr?->motif ?? '-',
                    'jenis_potongan'    => $dr?->jenis_potongan ?? '-',
                    'model_lengan_jahitan' => $dr?->lengan_jahitan ?? '-',
                    'item_details'      => $order->itemDetails?->map(fn($d) => [
                        'no_punggung'  => $d->no_punggung,
                        'nama_punggung' => $d->nama_punggung,
                        'model_lengan' => $d->model_lengan,
                        'size'         => $d->size,
                        'keterangan'   => $d->keterangan,
                    ])->values()->toArray() ?? [],
                    'notes'             => nl2br(e($allNotes)),
                    'total_qty'         => $order->orderItems->sum('qty'),
                    'sizes'             => $sizes,
                    'reference_files'   => $dr?->logo ? [asset('storage/' . $dr->logo)] : [],
                    'design_files'      => collect($dr?->design_files ?? [])
                        ->reject(fn($f) => isset($f['role']) && $f['role'] !== 'pola')
                        ->map(function ($f) {
                            $fullPath = storage_path('app/public/' . $f['path']);
                            $width = null;
                            $height = null;
                            if (isset($f['type']) && str_starts_with($f['type'], 'image/') && file_exists($fullPath)) {
                                $imgSize = @getimagesize($fullPath);
                                if ($imgSize) {
                                    $width = $imgSize[0];
                                    $height = $imgSize[1];
                                }
                            }
                            return [
                                'name'   => $f['name'] ?? 'File',
                                'type'   => $f['type'] ?? 'application/octet-stream',
                                'path'   => asset('storage/' . $f['path']),
                                'width'  => $width,
                                'height' => $height,
                            ];
                        })->values()->toArray(),
                    'history_notes'     => $historyNotes,
                ];
            })
            ->values()
            ->toArray();

        return view('internal.produksi', compact('orders'));
    }

    public function updateStatus(UpdateProductionStatusRequest $request, Order $order)
    {
        $data = $request->validated();

        $user = auth()->user();

        if (!in_array($user->role->name, ['Produksi', 'Super Admin', 'Manager'])) {
            return response()->json([
                'success' => false,
                'message' => 'Anda tidak memiliki izin untuk memperbarui status produksi.',
            ], 403);
        }

        $oldStatus = $order->status;

        $statusMap = [
            'proses_printing'  => ['stage' => 'printing', 'order_status' => 'siap_cetak'],
            'selesai_printing' => ['stage' => 'jahit',    'order_status' => 'diproduksi'],
            'proses_jahit'     => ['stage' => 'jahit',    'order_status' => 'diproduksi'],
            'selesai_jahit'    => ['stage' => 'qc',       'order_status' => 'diproduksi'],
            'proses_qc'        => ['stage' => 'qc',       'order_status' => 'diproduksi'],
            'selesai_qc'       => ['stage' => null,       'order_status' => 'selesai'],
            'revisi_qc'        => ['stage' => null,       'order_status' => 'diproduksi'], // stage from target_stage
        ];

        $mapping = $statusMap[$data['action']];
        $newOrderStatus = $mapping['order_status'];
        $newStage = $mapping['stage'];

        DB::transaction(function () use ($order, $newOrderStatus, $newStage, $data, $user) {
            $updateData = ['status' => $newOrderStatus];

            if ($data['action'] === 'revisi_qc') {
                $updateData['production_stage'] = $data['target_stage'] ?? 'jahit';
            } elseif ($newStage) {
                $updateData['production_stage'] = $newStage;
            } else {
                $updateData['production_stage'] = null;
            }

            $order->update($updateData);

            $order->statusHistories()->create([
                'status'     => $newOrderStatus,
                'changed_by' => $user->id,
                'notes'      => $data['notes'] ?? ('Produksi: ' . str_replace('_', ' ', $data['action'])),
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        });

        $notifType = str_starts_with($data['action'], 'selesai') ? 'production_done' : 'production_update';

        Notification::sendToAllStaff(
            $notifType,
            $newOrderStatus === 'selesai' ? 'Pesanan Selesai' : 'Update Produksi',
            $newOrderStatus === 'selesai'
                ? "Pesanan <strong>{$order->order_number}</strong> telah selesai diproduksi."
                : "Produksi pesanan <strong>{$order->order_number}</strong> telah diupdate oleh <strong>{$user->name}</strong>.",
            [
                'initials' => collect(explode(' ', $user->name))->map(fn($w) => substr($w, 0, 1))->take(2)->implode(''),
                'role' => $user->role->name,
                'role_initial' => substr($user->role->name, 0, 1),
                'role_color' => '#0284c7',
                'order_number' => $order->order_number,
            ]
        );

        if ($newOrderStatus === 'selesai') {
            Notification::sendToCustomer(
                $order->user_id,
                'production_done',
                'Pesanan Selesai',
                'Pesanan ' . $order->order_number . ' telah selesai diproduksi dan siap untuk dikirim/diambil.',
                [
                    'order_number' => $order->order_number,
                ]
            );
        }

        return response()->json([
            'success' => true,
            'message' => $newOrderStatus === 'selesai'
                ? 'Pesanan selesai diproduksi.'
                : 'Status produksi berhasil diperbarui.',
            'production_stage' => $newStage,
            'status' => $newOrderStatus,
            'target_stage' => $data['action'] === 'revisi_qc' ? ($data['target_stage'] ?? 'jahit') : null,
        ]);
    }
}
